authors:
   gbvitrano:
    name: Giovan Battista Vitrano
    description: Autore
    avatar: https://github.com/gbvitrano.png 
   aborruso:
    name: Andrea Borruso
    description: Autore
    avatar: https://github.com/aborruso.png
   pigreco:
    name: Totò Fiandaca
    description: Autore
    avatar: https://github.com/pigreco.png
   cirospat:
    name: Ciro Spataro
    description: Autore
    avatar: https://github.com/cirospat.png
